/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvitationRouteImport } from './routes/invitation'
import { Route as AuthPasswordChangedRouteImport } from './routes/auth-password-changed'
import { Route as AuthErrorRouteImport } from './routes/auth-error'
import { Route as AuthEmailVerifiedRouteImport } from './routes/auth-email-verified'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/app/users'
import { Route as AppTenantsRouteImport } from './routes/app/tenants'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppLibraryRouteImport } from './routes/app/library'
import { Route as AppAnnouncementsRouteImport } from './routes/app/announcements'
import { Route as AppAccountRouteImport } from './routes/app/account'
import { Route as AppTIndexRouteImport } from './routes/app/t.index'
import { Route as AppTTenantIdRouteImport } from './routes/app/t.$tenantId'
import { Route as AppTTenantIdIndexRouteImport } from './routes/app/t.$tenantId.index'
import { Route as AppTTenantIdWlanRouteImport } from './routes/app/t.$tenantId.wlan'
import { Route as AppTTenantIdVlanRouteImport } from './routes/app/t.$tenantId.vlan'
import { Route as AppTTenantIdSettingsRouteImport } from './routes/app/t.$tenantId.settings'
import { Route as AppTTenantIdResourcesRouteImport } from './routes/app/t.$tenantId.resources'
import { Route as AppTTenantIdRacksRouteImport } from './routes/app/t.$tenantId.racks'
import { Route as AppTTenantIdLocationsRouteImport } from './routes/app/t.$tenantId.locations'
import { Route as AppTTenantIdDashboardRouteImport } from './routes/app/t.$tenantId.dashboard'
import { Route as AppTTenantIdActivityRouteImport } from './routes/app/t.$tenantId.activity'
import { Route as AppTTenantIdLocationsIndexRouteImport } from './routes/app/t.$tenantId.locations_.index'
import { Route as AppTTenantIdLocationsLocationIdIndexRouteImport } from './routes/app/t.$tenantId.locations.$locationId.index'
import { Route as AppTTenantIdLocationsLocationIdDevicesRouteImport } from './routes/app/t.$tenantId.locations.$locationId.devices'
import { Route as AppTTenantIdLocationsLocationIdDevicesIndexRouteImport } from './routes/app/t.$tenantId.locations.$locationId.devices_.index'
import { Route as AppTTenantIdLocationsLocationIdDevicesDeviceIdRouteImport } from './routes/app/t.$tenantId.locations.$locationId.devices.$deviceId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationRoute = InvitationRouteImport.update({
  id: '/invitation',
  path: '/invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPasswordChangedRoute = AuthPasswordChangedRouteImport.update({
  id: '/auth-password-changed',
  path: '/auth-password-changed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth-error',
  path: '/auth-error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEmailVerifiedRoute = AuthEmailVerifiedRouteImport.update({
  id: '/auth-email-verified',
  path: '/auth-email-verified',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsRoute = AppTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppTIndexRoute = AppTIndexRouteImport.update({
  id: '/t/',
  path: '/t/',
  getParentRoute: () => AppRoute,
} as any)
const AppTTenantIdRoute = AppTTenantIdRouteImport.update({
  id: '/t/$tenantId',
  path: '/t/$tenantId',
  getParentRoute: () => AppRoute,
} as any)
const AppTTenantIdIndexRoute = AppTTenantIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTTenantIdRoute,
} as any)
const AppTTenantIdWlanRoute = AppTTenantIdWlanRouteImport.update({
  id: '/wlan',
  path: '/wlan',
  getParentRoute: () => AppTTenantIdRoute,
} as any)
const AppTTenantIdVlanRoute = AppTTenantIdVlanRouteImport.update({
  id: '/vlan',
  path: '/vlan',
  getParentRoute: () => AppTTenantIdRoute,
} as any)
const AppTTenantIdSettingsRoute = AppTTenantIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppTTenantIdRoute,
} as any)
const AppTTenantIdResourcesRoute = AppTTenantIdResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppTTenantIdRoute,
} as any)
const AppTTenantIdRacksRoute = AppTTenantIdRacksRouteImport.update({
  id: '/racks',
  path: '/racks',
  getParentRoute: () => AppTTenantIdRoute,
} as any)
const AppTTenantIdLocationsRoute = AppTTenantIdLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AppTTenantIdRoute,
} as any)
const AppTTenantIdDashboardRoute = AppTTenantIdDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppTTenantIdRoute,
} as any)
const AppTTenantIdActivityRoute = AppTTenantIdActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppTTenantIdRoute,
} as any)
const AppTTenantIdLocationsIndexRoute =
  AppTTenantIdLocationsIndexRouteImport.update({
    id: '/locations_/',
    path: '/locations/',
    getParentRoute: () => AppTTenantIdRoute,
  } as any)
const AppTTenantIdLocationsLocationIdIndexRoute =
  AppTTenantIdLocationsLocationIdIndexRouteImport.update({
    id: '/$locationId/',
    path: '/$locationId/',
    getParentRoute: () => AppTTenantIdLocationsRoute,
  } as any)
const AppTTenantIdLocationsLocationIdDevicesRoute =
  AppTTenantIdLocationsLocationIdDevicesRouteImport.update({
    id: '/$locationId/devices',
    path: '/$locationId/devices',
    getParentRoute: () => AppTTenantIdLocationsRoute,
  } as any)
const AppTTenantIdLocationsLocationIdDevicesIndexRoute =
  AppTTenantIdLocationsLocationIdDevicesIndexRouteImport.update({
    id: '/$locationId/devices_/',
    path: '/$locationId/devices/',
    getParentRoute: () => AppTTenantIdLocationsRoute,
  } as any)
const AppTTenantIdLocationsLocationIdDevicesDeviceIdRoute =
  AppTTenantIdLocationsLocationIdDevicesDeviceIdRouteImport.update({
    id: '/$deviceId',
    path: '/$deviceId',
    getParentRoute: () => AppTTenantIdLocationsLocationIdDevicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth-email-verified': typeof AuthEmailVerifiedRoute
  '/auth-error': typeof AuthErrorRoute
  '/auth-password-changed': typeof AuthPasswordChangedRoute
  '/invitation': typeof InvitationRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/account': typeof AppAccountRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/library': typeof AppLibraryRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tenants': typeof AppTenantsRoute
  '/app/users': typeof AppUsersRoute
  '/app/t/$tenantId': typeof AppTTenantIdRouteWithChildren
  '/app/t/': typeof AppTIndexRoute
  '/app/t/$tenantId/activity': typeof AppTTenantIdActivityRoute
  '/app/t/$tenantId/dashboard': typeof AppTTenantIdDashboardRoute
  '/app/t/$tenantId/locations': typeof AppTTenantIdLocationsRouteWithChildren
  '/app/t/$tenantId/racks': typeof AppTTenantIdRacksRoute
  '/app/t/$tenantId/resources': typeof AppTTenantIdResourcesRoute
  '/app/t/$tenantId/settings': typeof AppTTenantIdSettingsRoute
  '/app/t/$tenantId/vlan': typeof AppTTenantIdVlanRoute
  '/app/t/$tenantId/wlan': typeof AppTTenantIdWlanRoute
  '/app/t/$tenantId/': typeof AppTTenantIdIndexRoute
  '/app/t/$tenantId/locations/': typeof AppTTenantIdLocationsIndexRoute
  '/app/t/$tenantId/locations/$locationId/devices': typeof AppTTenantIdLocationsLocationIdDevicesRouteWithChildren
  '/app/t/$tenantId/locations/$locationId/': typeof AppTTenantIdLocationsLocationIdIndexRoute
  '/app/t/$tenantId/locations/$locationId/devices/$deviceId': typeof AppTTenantIdLocationsLocationIdDevicesDeviceIdRoute
  '/app/t/$tenantId/locations/$locationId/devices/': typeof AppTTenantIdLocationsLocationIdDevicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth-email-verified': typeof AuthEmailVerifiedRoute
  '/auth-error': typeof AuthErrorRoute
  '/auth-password-changed': typeof AuthPasswordChangedRoute
  '/invitation': typeof InvitationRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/account': typeof AppAccountRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/library': typeof AppLibraryRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tenants': typeof AppTenantsRoute
  '/app/users': typeof AppUsersRoute
  '/app/t': typeof AppTIndexRoute
  '/app/t/$tenantId/activity': typeof AppTTenantIdActivityRoute
  '/app/t/$tenantId/dashboard': typeof AppTTenantIdDashboardRoute
  '/app/t/$tenantId/locations': typeof AppTTenantIdLocationsIndexRoute
  '/app/t/$tenantId/racks': typeof AppTTenantIdRacksRoute
  '/app/t/$tenantId/resources': typeof AppTTenantIdResourcesRoute
  '/app/t/$tenantId/settings': typeof AppTTenantIdSettingsRoute
  '/app/t/$tenantId/vlan': typeof AppTTenantIdVlanRoute
  '/app/t/$tenantId/wlan': typeof AppTTenantIdWlanRoute
  '/app/t/$tenantId': typeof AppTTenantIdIndexRoute
  '/app/t/$tenantId/locations/$locationId/devices': typeof AppTTenantIdLocationsLocationIdDevicesIndexRoute
  '/app/t/$tenantId/locations/$locationId': typeof AppTTenantIdLocationsLocationIdIndexRoute
  '/app/t/$tenantId/locations/$locationId/devices/$deviceId': typeof AppTTenantIdLocationsLocationIdDevicesDeviceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth-email-verified': typeof AuthEmailVerifiedRoute
  '/auth-error': typeof AuthErrorRoute
  '/auth-password-changed': typeof AuthPasswordChangedRoute
  '/invitation': typeof InvitationRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/account': typeof AppAccountRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/library': typeof AppLibraryRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tenants': typeof AppTenantsRoute
  '/app/users': typeof AppUsersRoute
  '/app/t/$tenantId': typeof AppTTenantIdRouteWithChildren
  '/app/t/': typeof AppTIndexRoute
  '/app/t/$tenantId/activity': typeof AppTTenantIdActivityRoute
  '/app/t/$tenantId/dashboard': typeof AppTTenantIdDashboardRoute
  '/app/t/$tenantId/locations': typeof AppTTenantIdLocationsRouteWithChildren
  '/app/t/$tenantId/racks': typeof AppTTenantIdRacksRoute
  '/app/t/$tenantId/resources': typeof AppTTenantIdResourcesRoute
  '/app/t/$tenantId/settings': typeof AppTTenantIdSettingsRoute
  '/app/t/$tenantId/vlan': typeof AppTTenantIdVlanRoute
  '/app/t/$tenantId/wlan': typeof AppTTenantIdWlanRoute
  '/app/t/$tenantId/': typeof AppTTenantIdIndexRoute
  '/app/t/$tenantId/locations_/': typeof AppTTenantIdLocationsIndexRoute
  '/app/t/$tenantId/locations/$locationId/devices': typeof AppTTenantIdLocationsLocationIdDevicesRouteWithChildren
  '/app/t/$tenantId/locations/$locationId/': typeof AppTTenantIdLocationsLocationIdIndexRoute
  '/app/t/$tenantId/locations/$locationId/devices/$deviceId': typeof AppTTenantIdLocationsLocationIdDevicesDeviceIdRoute
  '/app/t/$tenantId/locations/$locationId/devices_/': typeof AppTTenantIdLocationsLocationIdDevicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth-email-verified'
    | '/auth-error'
    | '/auth-password-changed'
    | '/invitation'
    | '/login'
    | '/register'
    | '/app/account'
    | '/app/announcements'
    | '/app/library'
    | '/app/settings'
    | '/app/tenants'
    | '/app/users'
    | '/app/t/$tenantId'
    | '/app/t/'
    | '/app/t/$tenantId/activity'
    | '/app/t/$tenantId/dashboard'
    | '/app/t/$tenantId/locations'
    | '/app/t/$tenantId/racks'
    | '/app/t/$tenantId/resources'
    | '/app/t/$tenantId/settings'
    | '/app/t/$tenantId/vlan'
    | '/app/t/$tenantId/wlan'
    | '/app/t/$tenantId/'
    | '/app/t/$tenantId/locations/'
    | '/app/t/$tenantId/locations/$locationId/devices'
    | '/app/t/$tenantId/locations/$locationId/'
    | '/app/t/$tenantId/locations/$locationId/devices/$deviceId'
    | '/app/t/$tenantId/locations/$locationId/devices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth-email-verified'
    | '/auth-error'
    | '/auth-password-changed'
    | '/invitation'
    | '/login'
    | '/register'
    | '/app/account'
    | '/app/announcements'
    | '/app/library'
    | '/app/settings'
    | '/app/tenants'
    | '/app/users'
    | '/app/t'
    | '/app/t/$tenantId/activity'
    | '/app/t/$tenantId/dashboard'
    | '/app/t/$tenantId/locations'
    | '/app/t/$tenantId/racks'
    | '/app/t/$tenantId/resources'
    | '/app/t/$tenantId/settings'
    | '/app/t/$tenantId/vlan'
    | '/app/t/$tenantId/wlan'
    | '/app/t/$tenantId'
    | '/app/t/$tenantId/locations/$locationId/devices'
    | '/app/t/$tenantId/locations/$locationId'
    | '/app/t/$tenantId/locations/$locationId/devices/$deviceId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth-email-verified'
    | '/auth-error'
    | '/auth-password-changed'
    | '/invitation'
    | '/login'
    | '/register'
    | '/app/account'
    | '/app/announcements'
    | '/app/library'
    | '/app/settings'
    | '/app/tenants'
    | '/app/users'
    | '/app/t/$tenantId'
    | '/app/t/'
    | '/app/t/$tenantId/activity'
    | '/app/t/$tenantId/dashboard'
    | '/app/t/$tenantId/locations'
    | '/app/t/$tenantId/racks'
    | '/app/t/$tenantId/resources'
    | '/app/t/$tenantId/settings'
    | '/app/t/$tenantId/vlan'
    | '/app/t/$tenantId/wlan'
    | '/app/t/$tenantId/'
    | '/app/t/$tenantId/locations_/'
    | '/app/t/$tenantId/locations/$locationId/devices'
    | '/app/t/$tenantId/locations/$locationId/'
    | '/app/t/$tenantId/locations/$locationId/devices/$deviceId'
    | '/app/t/$tenantId/locations/$locationId/devices_/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthEmailVerifiedRoute: typeof AuthEmailVerifiedRoute
  AuthErrorRoute: typeof AuthErrorRoute
  AuthPasswordChangedRoute: typeof AuthPasswordChangedRoute
  InvitationRoute: typeof InvitationRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation': {
      id: '/invitation'
      path: '/invitation'
      fullPath: '/invitation'
      preLoaderRoute: typeof InvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-password-changed': {
      id: '/auth-password-changed'
      path: '/auth-password-changed'
      fullPath: '/auth-password-changed'
      preLoaderRoute: typeof AuthPasswordChangedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-error': {
      id: '/auth-error'
      path: '/auth-error'
      fullPath: '/auth-error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-email-verified': {
      id: '/auth-email-verified'
      path: '/auth-email-verified'
      fullPath: '/auth-email-verified'
      preLoaderRoute: typeof AuthEmailVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tenants': {
      id: '/app/tenants'
      path: '/tenants'
      fullPath: '/app/tenants'
      preLoaderRoute: typeof AppTenantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/announcements': {
      id: '/app/announcements'
      path: '/announcements'
      fullPath: '/app/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/t/': {
      id: '/app/t/'
      path: '/t'
      fullPath: '/app/t/'
      preLoaderRoute: typeof AppTIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/t/$tenantId': {
      id: '/app/t/$tenantId'
      path: '/t/$tenantId'
      fullPath: '/app/t/$tenantId'
      preLoaderRoute: typeof AppTTenantIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/t/$tenantId/': {
      id: '/app/t/$tenantId/'
      path: '/'
      fullPath: '/app/t/$tenantId/'
      preLoaderRoute: typeof AppTTenantIdIndexRouteImport
      parentRoute: typeof AppTTenantIdRoute
    }
    '/app/t/$tenantId/wlan': {
      id: '/app/t/$tenantId/wlan'
      path: '/wlan'
      fullPath: '/app/t/$tenantId/wlan'
      preLoaderRoute: typeof AppTTenantIdWlanRouteImport
      parentRoute: typeof AppTTenantIdRoute
    }
    '/app/t/$tenantId/vlan': {
      id: '/app/t/$tenantId/vlan'
      path: '/vlan'
      fullPath: '/app/t/$tenantId/vlan'
      preLoaderRoute: typeof AppTTenantIdVlanRouteImport
      parentRoute: typeof AppTTenantIdRoute
    }
    '/app/t/$tenantId/settings': {
      id: '/app/t/$tenantId/settings'
      path: '/settings'
      fullPath: '/app/t/$tenantId/settings'
      preLoaderRoute: typeof AppTTenantIdSettingsRouteImport
      parentRoute: typeof AppTTenantIdRoute
    }
    '/app/t/$tenantId/resources': {
      id: '/app/t/$tenantId/resources'
      path: '/resources'
      fullPath: '/app/t/$tenantId/resources'
      preLoaderRoute: typeof AppTTenantIdResourcesRouteImport
      parentRoute: typeof AppTTenantIdRoute
    }
    '/app/t/$tenantId/racks': {
      id: '/app/t/$tenantId/racks'
      path: '/racks'
      fullPath: '/app/t/$tenantId/racks'
      preLoaderRoute: typeof AppTTenantIdRacksRouteImport
      parentRoute: typeof AppTTenantIdRoute
    }
    '/app/t/$tenantId/locations': {
      id: '/app/t/$tenantId/locations'
      path: '/locations'
      fullPath: '/app/t/$tenantId/locations'
      preLoaderRoute: typeof AppTTenantIdLocationsRouteImport
      parentRoute: typeof AppTTenantIdRoute
    }
    '/app/t/$tenantId/dashboard': {
      id: '/app/t/$tenantId/dashboard'
      path: '/dashboard'
      fullPath: '/app/t/$tenantId/dashboard'
      preLoaderRoute: typeof AppTTenantIdDashboardRouteImport
      parentRoute: typeof AppTTenantIdRoute
    }
    '/app/t/$tenantId/activity': {
      id: '/app/t/$tenantId/activity'
      path: '/activity'
      fullPath: '/app/t/$tenantId/activity'
      preLoaderRoute: typeof AppTTenantIdActivityRouteImport
      parentRoute: typeof AppTTenantIdRoute
    }
    '/app/t/$tenantId/locations_/': {
      id: '/app/t/$tenantId/locations_/'
      path: '/locations'
      fullPath: '/app/t/$tenantId/locations/'
      preLoaderRoute: typeof AppTTenantIdLocationsIndexRouteImport
      parentRoute: typeof AppTTenantIdRoute
    }
    '/app/t/$tenantId/locations/$locationId/': {
      id: '/app/t/$tenantId/locations/$locationId/'
      path: '/$locationId'
      fullPath: '/app/t/$tenantId/locations/$locationId/'
      preLoaderRoute: typeof AppTTenantIdLocationsLocationIdIndexRouteImport
      parentRoute: typeof AppTTenantIdLocationsRoute
    }
    '/app/t/$tenantId/locations/$locationId/devices': {
      id: '/app/t/$tenantId/locations/$locationId/devices'
      path: '/$locationId/devices'
      fullPath: '/app/t/$tenantId/locations/$locationId/devices'
      preLoaderRoute: typeof AppTTenantIdLocationsLocationIdDevicesRouteImport
      parentRoute: typeof AppTTenantIdLocationsRoute
    }
    '/app/t/$tenantId/locations/$locationId/devices_/': {
      id: '/app/t/$tenantId/locations/$locationId/devices_/'
      path: '/$locationId/devices'
      fullPath: '/app/t/$tenantId/locations/$locationId/devices/'
      preLoaderRoute: typeof AppTTenantIdLocationsLocationIdDevicesIndexRouteImport
      parentRoute: typeof AppTTenantIdLocationsRoute
    }
    '/app/t/$tenantId/locations/$locationId/devices/$deviceId': {
      id: '/app/t/$tenantId/locations/$locationId/devices/$deviceId'
      path: '/$deviceId'
      fullPath: '/app/t/$tenantId/locations/$locationId/devices/$deviceId'
      preLoaderRoute: typeof AppTTenantIdLocationsLocationIdDevicesDeviceIdRouteImport
      parentRoute: typeof AppTTenantIdLocationsLocationIdDevicesRoute
    }
  }
}

interface AppTTenantIdLocationsLocationIdDevicesRouteChildren {
  AppTTenantIdLocationsLocationIdDevicesDeviceIdRoute: typeof AppTTenantIdLocationsLocationIdDevicesDeviceIdRoute
}

const AppTTenantIdLocationsLocationIdDevicesRouteChildren: AppTTenantIdLocationsLocationIdDevicesRouteChildren =
  {
    AppTTenantIdLocationsLocationIdDevicesDeviceIdRoute:
      AppTTenantIdLocationsLocationIdDevicesDeviceIdRoute,
  }

const AppTTenantIdLocationsLocationIdDevicesRouteWithChildren =
  AppTTenantIdLocationsLocationIdDevicesRoute._addFileChildren(
    AppTTenantIdLocationsLocationIdDevicesRouteChildren,
  )

interface AppTTenantIdLocationsRouteChildren {
  AppTTenantIdLocationsLocationIdDevicesRoute: typeof AppTTenantIdLocationsLocationIdDevicesRouteWithChildren
  AppTTenantIdLocationsLocationIdIndexRoute: typeof AppTTenantIdLocationsLocationIdIndexRoute
  AppTTenantIdLocationsLocationIdDevicesIndexRoute: typeof AppTTenantIdLocationsLocationIdDevicesIndexRoute
}

const AppTTenantIdLocationsRouteChildren: AppTTenantIdLocationsRouteChildren = {
  AppTTenantIdLocationsLocationIdDevicesRoute:
    AppTTenantIdLocationsLocationIdDevicesRouteWithChildren,
  AppTTenantIdLocationsLocationIdIndexRoute:
    AppTTenantIdLocationsLocationIdIndexRoute,
  AppTTenantIdLocationsLocationIdDevicesIndexRoute:
    AppTTenantIdLocationsLocationIdDevicesIndexRoute,
}

const AppTTenantIdLocationsRouteWithChildren =
  AppTTenantIdLocationsRoute._addFileChildren(
    AppTTenantIdLocationsRouteChildren,
  )

interface AppTTenantIdRouteChildren {
  AppTTenantIdActivityRoute: typeof AppTTenantIdActivityRoute
  AppTTenantIdDashboardRoute: typeof AppTTenantIdDashboardRoute
  AppTTenantIdLocationsRoute: typeof AppTTenantIdLocationsRouteWithChildren
  AppTTenantIdRacksRoute: typeof AppTTenantIdRacksRoute
  AppTTenantIdResourcesRoute: typeof AppTTenantIdResourcesRoute
  AppTTenantIdSettingsRoute: typeof AppTTenantIdSettingsRoute
  AppTTenantIdVlanRoute: typeof AppTTenantIdVlanRoute
  AppTTenantIdWlanRoute: typeof AppTTenantIdWlanRoute
  AppTTenantIdIndexRoute: typeof AppTTenantIdIndexRoute
  AppTTenantIdLocationsIndexRoute: typeof AppTTenantIdLocationsIndexRoute
}

const AppTTenantIdRouteChildren: AppTTenantIdRouteChildren = {
  AppTTenantIdActivityRoute: AppTTenantIdActivityRoute,
  AppTTenantIdDashboardRoute: AppTTenantIdDashboardRoute,
  AppTTenantIdLocationsRoute: AppTTenantIdLocationsRouteWithChildren,
  AppTTenantIdRacksRoute: AppTTenantIdRacksRoute,
  AppTTenantIdResourcesRoute: AppTTenantIdResourcesRoute,
  AppTTenantIdSettingsRoute: AppTTenantIdSettingsRoute,
  AppTTenantIdVlanRoute: AppTTenantIdVlanRoute,
  AppTTenantIdWlanRoute: AppTTenantIdWlanRoute,
  AppTTenantIdIndexRoute: AppTTenantIdIndexRoute,
  AppTTenantIdLocationsIndexRoute: AppTTenantIdLocationsIndexRoute,
}

const AppTTenantIdRouteWithChildren = AppTTenantIdRoute._addFileChildren(
  AppTTenantIdRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTenantsRoute: typeof AppTenantsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppTTenantIdRoute: typeof AppTTenantIdRouteWithChildren
  AppTIndexRoute: typeof AppTIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTenantsRoute: AppTenantsRoute,
  AppUsersRoute: AppUsersRoute,
  AppTTenantIdRoute: AppTTenantIdRouteWithChildren,
  AppTIndexRoute: AppTIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthEmailVerifiedRoute: AuthEmailVerifiedRoute,
  AuthErrorRoute: AuthErrorRoute,
  AuthPasswordChangedRoute: AuthPasswordChangedRoute,
  InvitationRoute: InvitationRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
